2019-03-22 15:23:47,332 DEBUG   MainThread:21993 [wandb_config.py:_load_defaults():81] no defaults not found in config-defaults.yaml
2019-03-22 15:23:47,336 DEBUG   MainThread:21993 [cmd.py:execute():722] Popen(['git', 'cat-file', '--batch-check'], cwd=/home/jiyeong/1D_CNN/learning_collision_detection_real, universal_newlines=False, shell=None)
2019-03-22 15:23:47,340 DEBUG   MainThread:21993 [cmd.py:execute():722] Popen(['git', 'rev-parse', '--show-toplevel'], cwd=/home/jiyeong/1D_CNN/learning_collision_detection_real, universal_newlines=False, shell=None)
2019-03-22 15:23:47,348 DEBUG   MainThread:21993 [run_manager.py:__init__():452] Initialized sync for 1d_cnn/t5f5ybcb
2019-03-22 15:23:47,349 INFO    MainThread:21993 [run_manager.py:wrap_existing_process():986] wrapping existing process 21978
2019-03-22 15:23:47,349 WARNING MainThread:21993 [io_wrap.py:register():104] SIGWINCH handler was not None: <Handlers.SIG_DFL: 0>
2019-03-22 15:23:47,352 DEBUG   MainThread:21993 [connectionpool.py:_new_conn():813] Starting new HTTPS connection (1): pypi.org:443
2019-03-22 15:23:48,337 INFO    Thread-2  :21993 [run_manager.py:_on_file_created():576] file/dir created: /home/jiyeong/1D_CNN/learning_collision_detection_real/1DCNN/wandb/run-20190322_062346-t5f5ybcb/wandb-metadata.json
2019-03-22 15:23:52,517 DEBUG   MainThread:21993 [connectionpool.py:_make_request():393] https://pypi.org:443 "GET /pypi/wandb/json HTTP/1.1" 200 30799
2019-03-22 15:23:52,558 INFO    MainThread:21993 [run_manager.py:init_run():810] system metrics and metadata threads started
2019-03-22 15:23:52,559 INFO    MainThread:21993 [run_manager.py:wrap_existing_process():1003] informing user process we are ready to proceed
2019-03-22 15:23:52,559 INFO    MainThread:21993 [run_manager.py:_sync_etc():1059] entering loop for messages from user process
e are ready to proceed
2019-03-22 15:23:52,559 INFO    MainThread:21993 [t5f5ybcb:run_manager.py:_sync_etc():1059] entering loop for messages from user process
